<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQyOg6lZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQyOg6lZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQyOg6lZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQyOg6lZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQyOg6lZ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QyOg6lZ',
    'container.build_id' => 'f5384070',
    'container.build_time' => 1573574356,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQyOg6lZ');
