<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEr3OE0y\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEr3OE0y/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEr3OE0y.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEr3OE0y\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEr3OE0y\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Er3OE0y',
    'container.build_id' => 'ae414207',
    'container.build_time' => 1574290962,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEr3OE0y');
